### ISSUE TITLE
??

### ISSUE THREAD

**Issue by Aanchan77** [cmalf/blessnetwork-bot-js#2]
Help me bot npm start

/data/data/com.termux/files/home/blessnetwork-bot-js/idnode.js:2
export const NODE_IDS = [
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (node:internal/modules/cjs/loader:1378:20)
    at Module._compile (node:internal/modules/cjs/loader:1428:41)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/blessnetwork-bot-js/bless.js:3:22)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)

**Comment by crkerx** [comment]
> Help me bot npm start
> 
> /data/data/com.termux/files/home/blessnetwork-bot-js/idnode.js:2 export const NODE_IDS = [ ^^^^^^
> 
> SyntaxError: Unexpected token 'export' at wrapSafe (node:internal/modules/cjs/loader:1378:20) at Module._compile (node:internal/modules/cjs/loader:1428:41) at Module._extensions..js (node:internal/modules/cjs/loader:1548:10) at Module.load (node:internal/modules/cjs/loader:1288:32) at Module._load (node:internal/modules/cjs/loader:1104:12) at Module.require (node:internal/modules/cjs/loader:1311:19) at require (node:internal/modules/helpers:179:18) at Object. (/data/data/com.termux/files/home/blessnetwork-bot-js/bless.js:3:22) at Module._compile (node:internal/modules/cjs/loader:1469:14) at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)

same issue

**Comment by cmalf** [comment]
```bash
// Node IDs
export const NODE_IDS = [
    "12D3KooxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxqgeUjZmKNW3Nt",  // Node 1
    "12D3KooxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxqgeUjZmKNW3Nt",  // Node 2 etc
    "12D3KooxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxqgeUjZmKNW3Nt",
    "12D3KooxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxqgeUjZmKNW3Nt",
    "12D3KooxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxqgeUjZmKNW3Nt"
];
```
or 

```bash
export const NODE_IDS = [
    "12D3KooxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxqgeUjZmKNW3Nt",  // Node 1
];
```

### delete the line if you only use one nodeid (don't leave the line blank), if you want to have multiple accounts, just add there for new nodeid for new account (one account maximum 5 nodeid), but you need to use proxy to do it.

**Comment by crkerx** [comment]
> ```shell
> // Node IDs
> export const NODE_IDS = [
>     "12D3KooxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxqgeUjZmKNW3Nt",  // Node 1
>     "12D3KooxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxqgeUjZmKNW3Nt",  // Node 2 etc
>     "12D3KooxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxqgeUjZmKNW3Nt",
>     "12D3KooxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxqgeUjZmKNW3Nt",
>     "12D3KooxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxqgeUjZmKNW3Nt"
> ];
> ```
> 
> or
> 
> ```shell
> export const NODE_IDS = [
>     "12D3KooxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxqgeUjZmKNW3Nt",  // Node 1
> ];
> ```
> 
> ### delete the line if you only use one nodeid (don't leave the line blank), if you want to have multiple accounts, just add there for new nodeid for new account (one account maximum 5 nodeid), but you need to use proxy to do it.

![860fc3b5bd9200cc59831](https://github.com/user-attachments/assets/efe3c3df-99bc-489e-97fc-279ec3c10696)
![aa495ff221d59c8bc5c42](https://github.com/user-attachments/assets/1c5c1207-9bca-42ef-8ef3-c444740c0513)
I followed your instructions but still get the above error

**Comment by cmalf** [comment]
Fixed!

```bash
// idnode.js
const NODE_IDS = [
    "node_id_1",
    "node_id_2",
    "node_id_3"
    // Add more node IDs as needed
];

module.exports = {
    NODE_IDS
};


```

![Screenshot 2024-12-21 at 15 19 08](https://github.com/user-attachments/assets/50c5830c-4ecc-4dd5-b3b1-bb4b27a18300)

**Comment by crkerx** [comment]
thank you very much!
